/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package club;

/**
 *
 * @author tmkds
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonPayments = new javax.swing.JButton();
        jButtonSports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonPerformances = new javax.swing.JButton();
        jButtonPlayer = new javax.swing.JButton();
        jButtonTournaments = new javax.swing.JButton();
        jButtonCoaches = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sport Club Management System");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPayments.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPayments.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonPayments.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPayments.setText("Payments");
        jButtonPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 170, 40));

        jButtonSports.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSports.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonSports.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSports.setText("Sports");
        jButtonSports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSportsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSports, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 170, 40));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 80)); // NOI18N
        jLabel1.setText("Menu");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 230, -1));

        jButtonPerformances.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPerformances.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonPerformances.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPerformances.setText("Performances");
        jButtonPerformances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerformancesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPerformances, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 170, 40));

        jButtonPlayer.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPlayer.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonPlayer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlayer.setText("Players");
        jButtonPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayerActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 170, 40));

        jButtonTournaments.setBackground(new java.awt.Color(0, 0, 0));
        jButtonTournaments.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonTournaments.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTournaments.setText("Tournaments");
        jButtonTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTournamentsActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTournaments, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 170, 40));

        jButtonCoaches.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCoaches.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButtonCoaches.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCoaches.setText("Coaches");
        jButtonCoaches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoachesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCoaches, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 170, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menunew.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 950, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(987, 715));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    //======================Player Button=================================
    private void jButtonPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayerActionPerformed
        Player p =new Player();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPlayerActionPerformed

    
    //=========================Sport Button==========================
    private void jButtonSportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSportsActionPerformed
      sport s = new sport();
      s.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButtonSportsActionPerformed

    
    //=================coaches button===============================
    private void jButtonCoachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoachesActionPerformed
        coach c =new coach();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCoachesActionPerformed

    
    //======================Performance Button======================================
    private void jButtonPerformancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerformancesActionPerformed
        performance per=new performance();
        per.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPerformancesActionPerformed

    
    //============================Payments Button=================================
    private void jButtonPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentsActionPerformed
        Payment pay =new Payment();
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPaymentsActionPerformed

    
    //===============Tournaments Button========================
    private void jButtonTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTournamentsActionPerformed
        Tournament t =new Tournament();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonTournamentsActionPerformed

    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCoaches;
    private javax.swing.JButton jButtonPayments;
    private javax.swing.JButton jButtonPerformances;
    private javax.swing.JButton jButtonPlayer;
    private javax.swing.JButton jButtonSports;
    private javax.swing.JButton jButtonTournaments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
